FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
about.summary="container for the vcf workflow"

ENV PACKAGES="procps curl git build-essential libhdf5-dev libffi-dev r-base-core" \
PYTHON="python3 python3-pip python3-dev"

RUN apt-get update \
&& apt-get install -y $PACKAGES $PYTHON \
&& apt-get install -y python3-packaging \
&& git clone https://github.com/AlexOrlek/VCFMIX.git \
&& cd VCFMIX \
&& pip3 install --upgrade pip \
&& pip3 install -r requirements.txt \
&& python3 setup.py install
