FROM ubuntu:focal

LABEL maintainer="pricea35@cardiff.ac.uk" \
about.summary="container for the vcf workflow"

ENV PACKAGES="procps curl git build-essential libhdf5-dev libffi-dev r-base-core" \
PYTHON="python3 python3-pip python3-dev"

RUN apt-get update \
&& DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata \
&& apt-get install -y $PACKAGES $PYTHON \
&& apt-get install -y python3-packaging \
&& git clone https://github.com/AlexOrlek/VCFMIX.git \
&& cd VCFMIX \
&& pip3 install --upgrade pip \
&& pip3 install -r requirements.txt \
&& cd ..

RUN git clone https://github.com/oxfordmmm/gumpy \
&& cd gumpy \
&& pip3 install -r requirements.txt \
&& python3 setup.py build --force \
&& pip3 install . \
&& pip3 install bio \
&& cd ..

RUN git clone https://github.com/oxfordmmm/piezo.git \
&& cd piezo \
&& pip3 install -r requirements.txt \
&& python3 setup.py build --force \
&& pip3 install . \
&& cd ..

RUN git clone https://github.com/philipwfowler/sp3predict.git \
&& cd sp3predict \
&& sed -i 's:#! /usr/bin/env python:#!/usr/bin/env python3:g' bin/sp3predict.py \
&& python3 setup.py build --force \
&& pip3 install . \
&& cd ..

RUN git clone https://github.com/oxfordmmm/tuberculosis_amr_catalogues.git
