name: pytest
on:
  push:
    branches:
      - main
    paths:
      - 'bin/*.py'

  workflow_dispatch:
  
jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: python -m pip install --upgrade pip biopython pysam pytest
              
      - name: Test with pytest
        working-directory: tests/python
        run: |
          pytest 
